### ISSUE TITLE
Trouble installing Deepin Desktop Env on Ubuntu 14.04

### ISSUE THREAD

**Issue by sysads** [linuxdeepin/deepin-installer#6]
Hi

I am having trouble installing deepin desktop environment on ubuntu 14.04. getting error:

The following packages have unmet dependencies.
 dde-meta-core : Depends: deepin-desktop-environment but it is not going to be installed
                 Depends: dde-control-center but it is not going to be installed
E: Unable to correct problems, you have held broken packages

How do i sort this out. Thanks

**Comment by bbruno5** [comment]
There is incompatibilities on packages from dde-dock, dde-dock-applets and dde-meta-core.
Some libs are compilations for 64 bits and others for i386. And all this are generating issues to install that are insoluble, because create a eternal loop of incompatibility.
