### ISSUE TITLE
Unable to install deepin 2014.1 on a macbook pro

### ISSUE THREAD

**Issue by faisyl** [linuxdeepin/deepin-installer#7]
I'm having trouble getting this installed right off. Unfortunately, when booting, I can't seem to be able to switch off the nouveau driver. I tried dumping the bootin installer onto a usb disk and fiddling with the startup parameters in isolinux.cfg and suslinux.cfg, but I guess when booting in EFI mode, it doesn't read this. If I create it with bios support, it doesn't show up as a boot target. Is there any way I can make a custom installer with the nouveau.noaccel etc added to the boot args ? Or maybe I can get to deepin linux using a stock ubuntu 14.04 install ?

**Comment by manateelazycat** [comment]
Hi faisyl

Deepin 15.x can support Mac book (include Mac Pro) now!

Thanks for your report, please install lastest version of deepin in your Mac book. ;)

**Comment by Qinka** [comment]
@manateelazycat 
为啥我用的 15.4.1 的镜像也不能安装，出现deepin 的logo后，就只剩左上角的一个光标了，然后就不动了。。。
